name: Update README with Recent Activity

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with GitHub Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          COMMIT_MSG: "Update README with recent activity"
          MAX_LINES: 5
          GH_USERNAME: sammy200-ui
